---

- name: Write Host key to known hosts
  connection: local
  shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"

- name: Install Blinkstick Vizsualizer 
  hosts: transmit_node, receive_nodes
  remote_user: pi 
  become: yes
  become_method: sudo
  vars_files:
   - secrets.yml 
  roles:
    - common 
    - blinkstickviz 
    - reboot 
