---

- name: Install Blinkstick Vizsualizer 
  #  hosts: transmit_node, receive_nodes # Use only receive nodes if install bsvapp (Django App)
  hosts: receive_nodes
  remote_user: pi 
  become: yes
  become_method: sudo
  vars_files:
   - secrets.yml 
  roles:
    - common 
    - blinkstickviz 
    - updates 
      #    - reboot 
