---
- name: 
  hosts: transmit_node, receive_nodes
  connection: local
  remote_user: pi 
  become: yes
  become_method: sudo
  vars_files:
   - secrets.yml 
  roles:
    - common 
    - blinkstickviz 
    - reboot 
