---

- name: Install Useful Tools
  tags: common, base, useful_tools
  apt:
    name: '{{ packages }}'
    state: latest
    update_cache: yes
  vars:
   packages:
    - virtualenv
    - lynx
    - wget
    - curl
    - traceroute
    - jq
    - screen
    - nmap
    - unzip
    - ntpdate 
    - git 
    - rsync 
    - dnsutils 
    - net-tools 

- name: Install Python3
  tags: common, base, python 
  apt:
    name: '{{ packages }}'
    state: latest
  vars:
   packages:
    - python3
    - python3-pip

